services:
  - type: web
    name: pharmaOne
    runtime: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate"
    startCommand: "gunicorn conf.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.14.6
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: "pharmaOne.onrender.com"