# Generated by Django 6.1 on 2026-08-27 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_typerole_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='pharmacie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.pharmacie', verbose_name='pharmacieRole'),
        ),
    ]
