# Generated by Django 6.1 on 2026-08-29 03:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_role_pharmacie'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TauxChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux_usd_cdf', models.DecimalField(decimal_places=2, help_text='Ex: 1 USD = 2500 CDF', max_digits=12, verbose_name='Taux USD vers CDF')),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True, verbose_name='Taux actif')),
                ('pharmacie', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taux_change', to='app.pharmacie', verbose_name='Pharmacie')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur ayant défini le taux')),
            ],
            options={
                'verbose_name': 'Taux de change',
                'verbose_name_plural': 'Taux de change',
                'ordering': ['-date_mise_a_jour'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('est_actif', True)), fields=('pharmacie', 'est_actif'), name='unique_taux_actif_par_pharmacie')],
            },
        ),
    ]
