# Generated by Django 6.1 on 2026-08-31 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tauxchange'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('forme', models.CharField(choices=[('COMPRIME', 'Comprimé'), ('GELULE', 'Gélule'), ('SIROP', 'Sirop'), ('INJECTABLE', 'Injectable'), ('POMMADE', 'Pommade'), ('SUPPOSITOIRE', 'Suppositoire'), ('POUDRE', 'Poudre'), ('AUTRE', 'Autre')], default='COMPRIME', max_length=20)),
                ('categorie', models.CharField(choices=[('ANTIBIOTIQUE', 'Antibiotique'), ('ANTALGIQUE', 'Antalgique/Douleur'), ('ANTIPALUDEEN', 'Antipaludéen'), ('ANTIINFLAMMATOIRE', 'Anti-inflammatoire'), ('ANTIFONGIQUE', 'Antifongique'), ('VITAMINE', 'Vitamine/Complément'), ('ANTIHYPERTENSEUR', 'Antihypertenseur'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30)),
                ('dosage', models.CharField(blank=True, help_text='Ex: 500mg, 250mg/5ml', max_length=50, null=True)),
                ('fabricant', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('devise', models.CharField(choices=[('CDF', 'Franc Congolais'), ('USD', 'Dollar Américain')], default='CDF', help_text='Devise dans laquelle les prix ci-dessous sont exprimés', max_length=3)),
                ('quantite_par_carton', models.PositiveIntegerField(help_text='Nombre de pièces contenues dans un carton')),
                ('prix_achat_carton', models.DecimalField(decimal_places=2, help_text="Prix d'achat d'un carton entier", max_digits=12)),
                ('prix_vente_piece', models.DecimalField(decimal_places=2, help_text="Prix de vente d'une seule pièce", max_digits=12)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments', to='app.pharmacie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicaments_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Médicament',
                'verbose_name_plural': 'Médicaments',
                'ordering': ['nom'],
                'unique_together': {('pharmacie', 'nom', 'dosage')},
            },
        ),
    ]
