# Generated by Django 6.1 on 2026-09-01 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_medicament'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lot', models.CharField(max_length=100)),
                ('date_peremption', models.DateField()),
                ('date_achat', models.DateField(auto_now_add=True)),
                ('nombre_cartons', models.PositiveIntegerField(help_text='Nombre de cartons achetés lors de cette livraison')),
                ('quantite_piece', models.PositiveIntegerField(editable=False, help_text='Calculé automatiquement : nombre_cartons x quantite_par_carton du médicament')),
                ('quantite_restante', models.PositiveIntegerField(editable=False, help_text='Stock encore disponible pour ce lot (diminue à chaque vente)')),
                ('devise', models.CharField(choices=[('CDF', 'Franc Congolais'), ('USD', 'Dollar Américain')], default='CDF', max_length=3)),
                ('prix_achat_carton', models.DecimalField(decimal_places=2, max_digits=12)),
                ('prix_vente_piece', models.DecimalField(decimal_places=2, max_digits=12)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='app.medicament')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='app.pharmacie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ['date_peremption'],
            },
        ),
    ]
