# Generated by Django 6.1 on 2026-09-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantite_piece',
            field=models.PositiveIntegerField(editable=False, help_text='Calculé automatiquement : nombre_cartons × quantite_par_carton du médicament'),
        ),
    ]
