# Generated by Django 6.1 on 2026-09-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_stock_quantite_piece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='numero_lot',
            field=models.CharField(error_messages={'unique': 'Ce numéro de lot existe déjà. Veuillez saisir un numéro de lot différent.'}, max_length=100, unique=True),
        ),
    ]
