# Generated by Django 6.1 on 2026-09-01 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_stock_numero_lot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='numero_lot',
            field=models.CharField(help_text='Le numéro de lot doit être unique dans cette pharmacie.', max_length=100),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('pharmacie', 'numero_lot'), name='unique_numero_lot_par_pharmacie', violation_error_message='Ce numéro de lot existe déjà dans cette pharmacie.'),
        ),
    ]
