# Generated by Django 6.1 on 2026-09-02 00:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_stock_numero_lot_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée (approvisionnement)'), ('VENTE', 'Sortie (vente)'), ('AJUSTEMENT', 'Ajustement manuel'), ('PEREMPTION', 'Retrait pour péremption'), ('PERTE', 'Perte / casse')], max_length=20)),
                ('quantite', models.PositiveIntegerField(help_text='Quantité de pièces concernées par ce mouvement')),
                ('quantite_avant', models.PositiveIntegerField(editable=False, help_text='quantite_restante du lot avant ce mouvement')),
                ('quantite_apres', models.PositiveIntegerField(editable=False, help_text='quantite_restante du lot après ce mouvement')),
                ('motif', models.CharField(blank=True, help_text="Ex: numéro de vente, raison de l'ajustement...", max_length=255, null=True)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='app.medicament')),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='app.pharmacie')),
                ('stock', models.ForeignKey(help_text='Lot concerné par ce mouvement', on_delete=django.db.models.deletion.CASCADE, related_name='mouvements', to='app.stock')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mouvements_enregistres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
    ]
