# Generated by Django 6.1 on 2026-09-02 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_mouvementstock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée (approvisionnement)'), ('VENTE', 'Sortie (vente)'), ('ANNULATION', 'Annulation de vente'), ('AJUSTEMENT', 'Ajustement manuel'), ('PEREMPTION', 'Retrait pour péremption'), ('PERTE', 'Perte / casse')], max_length=20),
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('client_telephone', models.CharField(blank=True, max_length=30, null=True)),
                ('devise', models.CharField(choices=[('CDF', 'Franc Congolais'), ('USD', 'Dollar Américain')], default='CDF', max_length=3)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de paiement'), ('PARTIELLEMENT_PAYEE', 'Partiellement payée'), ('PAYEE', 'Payée intégralement'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=25)),
                ('date_vente', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='app.pharmacie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vente',
                'verbose_name_plural': 'Ventes',
                'ordering': ['-date_vente'],
            },
        ),
        migrations.CreateModel(
            name='LigneVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField()),
                ('prix_unitaire', models.DecimalField(decimal_places=2, help_text='Prix figé au moment de la vente', max_digits=12)),
                ('medicament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes_vente', to='app.medicament')),
                ('stock', models.ForeignKey(help_text="Lot précis d'où la quantité est déduite (choisi en FEFO)", on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='app.stock')),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='app.vente')),
            ],
            options={
                'verbose_name': 'Ligne de vente',
                'verbose_name_plural': 'Lignes de vente',
            },
        ),
    ]
