# Generated by Django 6.1 on 2026-09-02 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_mouvementstock_type_mouvement_vente_lignevente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lignevente',
            options={'ordering': ['id'], 'verbose_name': 'Ligne de vente', 'verbose_name_plural': 'Lignes de vente'},
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='medicament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='app.medicament'),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='prix_unitaire',
            field=models.DecimalField(decimal_places=2, editable=False, help_text='Prix figé depuis le lot au moment de la vente.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='stock',
            field=models.ForeignKey(help_text='Lot précis utilisé. Le système le choisit automatiquement avec FEFO.', on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='app.stock'),
        ),
        migrations.CreateModel(
            name='PaiementVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mode_paiement', models.CharField(choices=[('ESPECES', 'Espèces'), ('MOBILE_MONEY', 'Mobile Money'), ('CARTE', 'Carte bancaire'), ('VIREMENT', 'Virement bancaire'), ('AUTRE', 'Autre')], default='ESPECES', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100, null=True)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='paiements_ventes', to=settings.AUTH_USER_MODEL)),
                ('vente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='app.vente')),
            ],
            options={
                'verbose_name': 'Paiement de vente',
                'verbose_name_plural': 'Paiements de ventes',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
