# Generated by Django 6.1 on 2026-09-02 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_lignevente_options_alter_lignevente_medicament_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiementvente',
            name='reference',
            field=models.CharField(blank=True, help_text='Exemple : numéro de transaction Mobile Money.', max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='paiementvente',
            constraint=models.CheckConstraint(condition=models.Q(('montant__gt', 0)), name='paiement_vente_montant_positif'),
        ),
    ]
