# Generated by Django 6.1 on 2026-09-02 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_paiementvente_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiementvente',
            name='devise_paiement',
            field=models.CharField(choices=[('CDF', 'Franc Congolais'), ('USD', 'Dollar Américain')], default='CDF', help_text='Devise réellement donnée par le client : CDF ou USD.', max_length=3),
        ),
        migrations.AddField(
            model_name='paiementvente',
            name='montant_equivalent_vente',
            field=models.DecimalField(decimal_places=2, default=1, editable=False, help_text='Montant du paiement converti dans la devise de la vente. Utilisé pour calculer la dette.', max_digits=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paiementvente',
            name='taux_usd_cdf_applique',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Taux archivé lors du paiement. Exemple : 1 USD = 2300 CDF.', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paiementvente',
            name='montant',
            field=models.DecimalField(decimal_places=2, help_text='Montant réellement remis par le client dans la devise de paiement.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='paiementvente',
            name='reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
