# Generated by Django 6.1 on 2026-09-02 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_paiementvente_devise_paiement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lignevente',
            name='quantite_retournee',
            field=models.PositiveIntegerField(default=0, help_text='Quantité retournée par le client. Elle ne peut pas dépasser la quantité vendue.'),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='quantite',
            field=models.PositiveIntegerField(help_text='Quantité vendue au client.'),
        ),
        migrations.AlterField(
            model_name='lignevente',
            name='stock',
            field=models.ForeignKey(help_text='Lot précis utilisé pour la vente. Il est choisi automatiquement avec FEFO.', on_delete=django.db.models.deletion.PROTECT, related_name='lignes_vente', to='app.stock'),
        ),
    ]
