# Generated by Django 6.1 on 2026-09-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_lignevente_quantite_retournee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mouvementstock',
            name='type_mouvement',
            field=models.CharField(choices=[('ENTREE', 'Entrée (approvisionnement)'), ('VENTE', 'Sortie (vente)'), ('ANNULATION', 'Annulation de vente'), ('AJUSTEMENT', 'Ajustement manuel'), ('PEREMPTION', 'Retrait pour péremption'), ('PERTE', 'Perte / casse'), ('RETOUR_CLIENT', 'Retour client')], max_length=20),
        ),
    ]
