# Generated by Django 6.1 on 2026-09-07 03:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_mouvementstock_type_mouvement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pharmacie',
            options={'ordering': ['nom_pharmacie']},
        ),
        migrations.AlterUniqueTogether(
            name='medicament',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='pharmacie',
            name='user_pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pharmacies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='pharmacie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to='app.pharmacie', verbose_name='pharmacieRole'),
        ),
        migrations.AlterField(
            model_name='role',
            name='userRole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles', to=settings.AUTH_USER_MODEL, verbose_name='userRole'),
        ),
        migrations.AlterField(
            model_name='typerole',
            name='nom_typeRole',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AddIndex(
            model_name='pharmacie',
            index=models.Index(fields=['user_pharmacie'], name='app_pharmac_user_ph_41cdf6_idx'),
        ),
        migrations.AddConstraint(
            model_name='lignevente',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='ligne_vente_quantite_positive'),
        ),
        migrations.AddConstraint(
            model_name='lignevente',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_retournee__gte', 0)), name='ligne_vente_retour_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='lignevente',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_retournee__lte', models.F('quantite'))), name='ligne_vente_retour_max_quantite'),
        ),
        migrations.AddConstraint(
            model_name='medicament',
            constraint=models.UniqueConstraint(fields=('pharmacie', 'nom', 'dosage'), name='unique_medicament_pharmacie_nom_dosage'),
        ),
        migrations.AddConstraint(
            model_name='medicament',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_par_carton__gt', 0)), name='medicament_quantite_carton_positive'),
        ),
        migrations.AddConstraint(
            model_name='medicament',
            constraint=models.CheckConstraint(condition=models.Q(('prix_achat_carton__gt', 0)), name='medicament_prix_achat_positif'),
        ),
        migrations.AddConstraint(
            model_name='medicament',
            constraint=models.CheckConstraint(condition=models.Q(('prix_vente_piece__gt', 0)), name='medicament_prix_vente_positif'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite__gt', 0)), name='mouvement_quantite_positive'),
        ),
        migrations.AddConstraint(
            model_name='mouvementstock',
            constraint=models.CheckConstraint(condition=models.Q(('quantite_apres__gte', 0)), name='mouvement_quantite_apres_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('userRole', 'pharmacie', 'role'), name='unique_role_user_pharmacie_type'),
        ),
    ]
