# Generated by Django 6.1 on 2026-09-08 05:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_pharmacie_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(choices=[('LOYER', 'Loyer'), ('SALAIRE', 'Salaire'), ('ACHAT_FOURNITURE', 'Achat de fournitures'), ('TRANSPORT', 'Transport'), ('ENTRETIEN', 'Entretien'), ('ELECTRICITE_EAU', 'Électricité / Eau'), ('AUTRE', 'Autre')], default='AUTRE', max_length=30)),
                ('motif', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=14)),
                ('devise', models.CharField(choices=[('CDF', 'Franc congolais'), ('USD', 'Dollar américain')], default='CDF', max_length=3)),
                ('taux_usd_cdf_applique', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='depenses/justificatifs/')),
                ('date_depense', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('pharmacie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depenses', to='app.pharmacie')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='depenses_enregistrees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_depense'],
            },
        ),
    ]
